### ISSUE TITLE
Missing bean argument value: transactionOperations

### ISSUE THREAD

**Issue by KangoV** [KangoV/micronaut-test#1]
When trying to save a build at startup i get this stack trace:

```
Message: Missing bean argument value: transactionOperations
Path Taken: new HibernateJpaOperations(SessionFactory sessionFactory,[TransactionOperations transactionOperations],ExecutorService executorService)
io.micronaut.context.exceptions.BeanInstantiationException: Error instantiating bean of type  [io.micronaut.data.hibernate.operations.HibernateJpaOperations]

Message: Missing bean argument value: transactionOperations
Path Taken: new HibernateJpaOperations(SessionFactory sessionFactory,[TransactionOperations transactionOperations],ExecutorService executorService)
        at io.micronaut.context.AbstractParametrizedBeanDefinition.build(AbstractParametrizedBeanDefinition.java:103)
        at io.micronaut.context.BeanDefinitionDelegate.build(BeanDefinitionDelegate.java:109)
        at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1610)
        at io.micronaut.context.DefaultBeanContext.createAndRegisterSingleton(DefaultBeanContext.java:2319)
        at io.micronaut.context.DefaultBeanContext.getBeanForDefinition(DefaultBeanContext.java:2001)
        at io.micronaut.context.DefaultBeanContext.getBeanInternal(DefaultBeanContext.java:1975)
        at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:622)
        at io.micronaut.data.intercept.DataIntroductionAdvice.findInterceptor(DataIntroductionAdvice.java:105)
        at io.micronaut.data.intercept.DataIntroductionAdvice.intercept(DataIntroductionAdvice.java:76)
        at io.micronaut.aop.chain.MethodInterceptorChain.proceed(MethodInterceptorChain.java:69)
        at org.belldj.BuildsDao$Intercepted.save(Unknown Source)
        at org.belldj.Application.init(Application.java:43)
```

**Comment by KangoV** [comment]
Turns out i was pulling in an extra micronaut hibernate dependency that was conflicting.
